### ISSUE TITLE
Servo does not move

### ISSUE THREAD

**Issue by dmagyar** [lavolpecheprogramma/grbl-1-1h-servo#2]
Hi! I'm at a loss :( I try to get my servo working (I tried various SG90 servos as well as an MG995) but none of them are moving _AT_ALL_ when doing M3 S255, M3 S0 or M5. I tried the CNCShield as well as a bare atmega328 (nano module) and I'm down to the simplest setup possible:

1) the code from this repo as-is
2) atmega328p (nano) with the servo connected to GND, 5v and D11

If I upload a test sketch with a Servo library it happily rotates my servo on D11, no issues at all. 
Not sure if this project is monitored but any help is greatly appreciated.

**Comment by lavolpecheprogramma** [comment]
I don't know why.. i used an arduino uno and it works fine. Have you checked that your wires are in the right place? there are a lot of guide on internet!
