### ISSUE TITLE
Servo Travel Range

### ISSUE THREAD

**Issue by birdpump** [lavolpecheprogramma/grbl-1-1h-servo#4]
Hello, Is there a way to make the servo travel the full amount, it only goes 90 degrees and back.

Thanks

**Comment by Dudley1001** [comment]
Try changing the $30 value to 100. I recommended 255 but it was too much and 100 seems to work better

**Comment by birdpump** [comment]
I tried that but it still only goes 90°
What commands should I be using with $30 = 100
M3 S0 - to return ?
M3 S100 - for full turn?

**Comment by birdpump** [comment]
And does the motor type affect the rotation distance? 
I'm testing it with an MG996R, but am going to use it with an SG90 servo eventually

**Comment by Dudley1001** [comment]
try setting it to $30=100 to a lower value and see what happens. It seems like the smaller you go the more rotation you get but it may limit the resolution as well. You can also change your M3 S to over the 100 but be careful as I stripped a servo when it went too far. Those are the 2 parameters that you can play with.  I only need about 90 degrees so it works well enough for me.  I have seen some random movement on the servo at the m3 S0 position, more like servo gitters.

**Comment by birdpump** [comment]
ok, I tried that and it works for what I need. 

Thanks for the help :D
