### ISSUE TITLE
How To Change D11 pin to A5 pin

### ISSUE THREAD

**Issue by Damnned** [lavolpecheprogramma/grbl-1-1h-servo#6]
Hello Sir;
I have a All-in-one Board from Makerbase. I am Attaching the pin setup and Layout pictures too.
The D11 pin is used by laser on this board. They put an empty pin for the Servos (Analog 5 - Probe ) How Can i modify GRBL To use Analog pin 5 with the Servo. So we can have both Laser and servo connected to the board.  BTW most of the servo grbl firmwares disable Z-axis too I dont want to disable that too. I will use the machine as complex as possible 

Image Links - The Board is MKS DLC V2.0

https://ibb.co/j4S30J4
https://ibb.co/Pjg0hQk

**Comment by lavolpecheprogramma** [comment]
Hi,
sorry but i don't know if you can.
You can check [this file](https://github.com/lavolpecheprogramma/grbl-1-1h-servo/blob/master/grbl/cpu_map.h#L68), here there is the pin map list.
